#!/bin/sh

echo "$(date --rfc-3339=seconds): starting RASP update"
# red+green heartbeat = update mode
echo heartbeat > /sys/class/leds/led0/trigger
echo heartbeat > /sys/class/leds/led1/trigger

RASPDIR=/root/RASP
CHEFDIR=$RASPDIR/chef
cd $CHEFDIR

# run chef recipes
# TODO: call from default
CHEFOPTS="-z -c client.rb"
RECIPES=
RECIPES="${RECIPES}recipe[rasp-base-setup::heartbeat],"
RECIPES="${RECIPES}recipe[rasp-base-setup::motd],"
RECIPES="${RECIPES}recipe[rasp-base-setup::packages],"
RECIPES="${RECIPES}recipe[rasp-base-setup::firmware],"
RECIPES="${RECIPES}recipe[rasp-base-setup::rng],"

# todo: disable all chef-server settings
chef-client $CHEFOPTS -r $RECIPES

echo "$(date --rfc-3339=seconds): end of RASP update - rebooting"

reboot
