#!/bin/sh

echo "$(date --rfc-3339=seconds): starting RASP update"
# red+green heartbeat = update mode
echo heartbeat > /sys/class/leds/led0/trigger
echo heartbeat > /sys/class/leds/led1/trigger

RASPDIR=/root/RASP
CHEFDIR=$RASPDIR/chef
cd $CHEFDIR

# run chef recipes
CHEFOPTS="-z -c client.rb"

chef-client $CHEFOPTS -r "recipe[rasp-base-setup]"

echo "$(date --rfc-3339=seconds): end of RASP update - rebooting"

reboot
